artifact_location: /Users/MogaTaufiq/iCloud Drive (Archive)/Documents/Documents -
  Moga's Book/College/SEM 6/CapsPro/FineTuneYOLO/runs/mlflow/909220479089220635
creation_time: 1747576298054
experiment_id: '909220479089220635'
last_update_time: 1747576298054
lifecycle_stage: active
name: /Shared/Ultralytics
