artifact_location: /Users/MogaTaufiq/iCloud Drive (Archive)/Documents/Documents -
  Moga's Book/College/SEM 6/CapsPro/FineTuneYOLO/runs/mlflow/0
creation_time: 1747576298046
experiment_id: '0'
last_update_time: 1747576298046
lifecycle_stage: active
name: Default
